### ISSUE TITLE
gRPC implementation

### ISSUE THREAD

**Issue by mkschulze** [Humans-of-Julia/TypeDBClient.jl#20]
The Grakn core server communicates via [gRPC](https://grpc.io/) with it's clients.

Currently there is no working gRPC library in Julia. There are [gRPC.jl](https://github.com/tanmaykm/gRPC.jl) or [GRPC.jl](https://github.com/zhouyan/GRPC.jl), but these need to be checked and updated to a working state.

See issue #19 

The long term goal would require a native Julia implementation of gRPC. 
There has been several attempts to find people doing it here: #https://github.com/grpc/grpc/issues/24786
These let to an offer to get help facilitate the work, clarify requirements, do API reviews, set up interop tests as mentioned in the issue.

And here: https://discourse.julialang.org/t/grpc-api-community-request/51029
which led to no avail yet.

I also wrote a mail to @tanmaykm, he replied and might give it a shot to get existing stuff working back again (no promise), but may not be able to spend a lot of time on it. He would be happy if anyone else is willing to contribute.

[gRPC](https://grpc.io/docs/what-is-grpc/introduction/) is supposed to be a non trivial protocol, so I think it doesn't seem feasible to tackle this first and wait for completion until we can start with the GraknClient. 
![Bildschirmfoto 2021-01-17 um 00 25 06](https://user-images.githubusercontent.com/3390820/104827293-5cacdc00-585c-11eb-8409-9fdbb8c79f80.png)

Instead we should find an interim way by either calling into the Python gRPC library with Python or using Julias native [C calling functionality](https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/) to call into the [shared gRPC core library](https://github.com/grpc/grpc/tree/master/src/core), which is used by all client implementations. I guess this would require additional work, as the C lib seems to be more low level code.

Quickest solution to get started with developing the GraknClient.jl seems to be to call into Python and then see if somebody wants to take a leap on implementing/revamping a Julia native gRPC lib in the long run to eventualy avoid the Python call.

**Comment by FrankUrbach** [comment]
I think, we should find a place where we isolate the access to gRPC. For the first time we can use the Python implementation. We can replace this part If we have a working gRPC implementation in pure Julia.

**Comment by mkschulze** [comment]
Requested some guidance from the gRPC team here: https://github.com/grpc/grpc/issues/24786

**Comment by mkschulze** [comment]
Some description of high level semantics of the C gRPC can be viewd here for a reference maybe: #https://github.com/grpc/grpc/pull/15460/files
It hasn't been merged, because of nomenclature and too less time by the gRPC team to update but should show the concepts pretty close.

**Comment by FrankUrbach** [comment]
Imho for now we can close this issue because the implementation we have is for now sufficient.

**Comment by mkschulze** [comment]
> Imho for now we can close this issue because the implementation we have is for now sufficient.

there are still many open questions I think.

- is the gRPC.jl compatible or does it need more features?
- can we set up testing for it or get help by gRPC guys

The implementation is not finished I think, so why closing this.
