### ISSUE TITLE
Script prepare the translation from the java client to Julia

### ISSUE THREAD

**Issue by FrankUrbach** [Humans-of-Julia/TypeDBClient.jl#49]
The attached script runs not without preparing the right paths individually for your machine. Today, the command of preparing the generated file from proto-files didn't work. This should be done by hand. Above and below this every line can be executed after preparing the right paths. Because the issues don't allow attaching Julia files I will place the script file in the translate_java directory in the project GraknClient.jl.
This issue can be closed after the final translation is done.

**Comment by mkschulze** [comment]
This one right?: https://github.com/Humans-of-Julia/GraknClient.jl/blob/architecture-refactor/translate_java/Script_grakn_java_to_julia.jl

**Comment by FrankUrbach** [comment]
Yes. Unfortunately, you can't attach Julia files to an issue.

**Comment by mkschulze** [comment]
This can be closed right?

**Comment by FrankUrbach** [comment]
Yes. The job is done. I close this with this comment.
